name: 🚀 Deploy Laravel Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to Hostinger Dev
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u568526216/domains/gmrtransportexpress.com/public_html/dev

            echo "📥 Update source code"
            git fetch origin
            git reset --hard origin/dev

            echo "📦 Composer install"
            composer install \
              --no-interaction \
              --prefer-dist \
              --optimize-autoloader \
              --no-dev

            echo "🧹 Laravel optimize"
            php artisan key:generate --force || true
            php artisan migrate --force || true
            php artisan optimize:clear
            php artisan optimize
