name: 🚀 Deploy Laravel Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to Hostinger Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u568526216/domains/gmrtransportexpress.com/public_html

            echo "📥 Update source code"
            git fetch origin
            git reset --hard origin/production

            echo "📦 Composer install (prod)"
            composer install \
              --no-interaction \
              --prefer-dist \
              --optimize-autoloader \
              --no-dev

            echo "🧹 Laravel optimize (prod)"
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize
